name=MKE_S17_AGS10
version=1.1.0
author=MakerEdu.vn
maintainer=MakerEdu.vn
sentence=A robust library for the MKE-S17 AGS10 I2C TVOC IAQ sensor.
paragraph=Allows reading TVOC (up to 99,999 ppb), firmware version, and current resistance. Includes TwoWire support and CRC checking.
category=Sensors
url=https://github.com/makereduvn/MKE-S17-AGS10-I2C-TVOC-IAQ-SENSOR
architectures=*
includes=AGS10.h
